# Generated by Django 3.0.8 on 2020-07-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200715_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imageupload',
        ),
    ]
